# Generated by Django 5.1.3 on 2025-01-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sede', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('tipo_de_acompanamiento', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('detalles', models.TextField()),
            ],
        ),
    ]
