# Generated by Django 5.1.3 on 2025-01-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='facultad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='unidad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
