# Generated by Django 5.1.3 on 2025-01-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0002_queja_acompañamiento_ante_instancias_gubernamentales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='codigo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='queja',
            name='detalles',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='queja',
            name='estado',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='queja',
            name='fecha',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='queja',
            name='nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='queja',
            name='sede',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='queja',
            name='tipo_de_acompanamiento',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
