# Generated by Django 5.1.3 on 2025-01-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0002_queja_facultad_queja_unidad'),
        ('quejas', '0003_alter_queja_codigo_alter_queja_detalles_and_more'),
    ]

    operations = [
    ]
