# Generated by Django 5.1.3 on 2025-02-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0005_alter_queja_facultad_alter_queja_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='afectado_codigo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='queja',
            name='observaciones',
            field=models.CharField(default='hola', max_length=700),
        ),
    ]
