# Generated by Django 5.1.3 on 2025-07-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0006_queja_afectado_codigo_alter_queja_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queja',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='detalles',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='facultad',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='sede',
        ),
    ]
