# Generated by Django 5.1.3 on 2025-08-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0007_remove_queja_codigo_remove_queja_detalles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='afectado_vicerrectoria_adscrito',
            field=models.CharField(blank=True, max_length=52),
        ),
        migrations.AlterField(
            model_name='queja',
            name='agresor_vicerrectoria_adscrito',
            field=models.CharField(blank=True, max_length=52),
        ),
        migrations.AlterField(
            model_name='queja',
            name='reporta_vicerrectoria_adscrito',
            field=models.CharField(blank=True, max_length=52),
        ),
    ]
