# Generated by Django 5.1.3 on 2025-08-13 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0008_alter_queja_afectado_vicerrectoria_adscrito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialQueja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('queja_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_estados', to='quejas.queja')),
            ],
        ),
    ]
