# Generated by Django 5.1.3 on 2025-10-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0009_historialqueja'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialqueja',
            name='numero',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
