# Generated by Django 5.1.3 on 2025-10-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0011_cambioestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='afectado_correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='queja',
            name='reporta_correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
