# Generated by Django 5.1.3 on 2025-10-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0012_alter_queja_afectado_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='afectado_barrio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_documento_identidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_redes_apoyo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_tipo_documento_identidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_barrio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='prioridad',
            field=models.CharField(blank=True, default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='historialqueja',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historialqueja',
            name='tipo',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='queja',
            name='acompañamiento_ante_instancias_gubernamentales',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='queja',
            name='acompañamiento_solicitud_medidas_proteccion_inicial',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='queja',
            name='afectado_detalles_caso',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='queja',
            name='afectado_tipo_vbg_os',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='queja',
            name='asistencia_juridica',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='queja',
            name='desea_activar_ruta_atencion_integral',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='queja',
            name='interponer_queja_al_comite_asusntos_internos_disciplinarios',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='queja',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='queja',
            name='orientacion_psicologica',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='queja',
            name='recibir_asesoria_orientacion_sociopedagogica',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
