# Generated by Django 5.1.3 on 2025-10-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0013_queja_afectado_barrio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='afectado_ciudad_origen',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_ciudad_origen',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_detalles_caso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_factores_riesgo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_tiene_denuncias',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
