# Generated by Django 5.1.3 on 2025-10-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0014_queja_afectado_ciudad_origen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queja',
            old_name='agresor_detalles_caso',
            new_name='agresor_detalles_denuncias',
        ),
    ]
