# Generated by Django 5.1.3 on 2025-10-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0015_rename_agresor_detalles_caso_queja_agresor_detalles_denuncias'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='afectado_denuncias_previas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_ha_hecho_denuncia',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
