# Generated by Django 5.1.3 on 2025-10-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0016_queja_afectado_denuncias_previas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='estado',
            field=models.CharField(blank=True, default='Recepción', max_length=30),
        ),
    ]
