# Generated by Django 5.1.3 on 2025-10-28 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0017_alter_queja_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaAcusada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('sexo', models.CharField(blank=True, max_length=30)),
                ('edad', models.CharField(blank=True, max_length=30)),
                ('estamento', models.CharField(blank=True, max_length=30)),
                ('vicerrectoria_adscrito', models.CharField(blank=True, max_length=52)),
                ('dependencia', models.CharField(blank=True, max_length=30)),
                ('programa_academico', models.CharField(blank=True, max_length=30)),
                ('facultad', models.CharField(blank=True, max_length=30)),
                ('sede', models.CharField(blank=True, max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('condicion_etnico_racial', models.CharField(blank=True, max_length=30)),
                ('tiene_discapacidad', models.CharField(blank=True, max_length=30)),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=30)),
                ('identidad_genero', models.CharField(blank=True, max_length=30)),
                ('orientacion_sexual', models.CharField(blank=True, max_length=30)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('barrio', models.CharField(blank=True, max_length=30)),
                ('ciudad_origen', models.CharField(blank=True, max_length=30, null=True)),
                ('factores_riesgo', models.TextField(blank=True, null=True)),
                ('tiene_denuncias', models.CharField(blank=True, max_length=3)),
                ('detalles_denuncias', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonaAfectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('sexo', models.CharField(blank=True, max_length=30)),
                ('edad', models.CharField(blank=True, max_length=30)),
                ('estamento', models.CharField(blank=True, max_length=30)),
                ('vicerrectoria_adscrito', models.CharField(blank=True, max_length=52)),
                ('dependencia', models.CharField(blank=True, max_length=30)),
                ('programa_academico', models.CharField(blank=True, max_length=30)),
                ('facultad', models.CharField(blank=True, max_length=30)),
                ('sede', models.CharField(blank=True, max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('condicion_etnico_racial', models.CharField(blank=True, max_length=30)),
                ('tiene_discapacidad', models.CharField(blank=True, max_length=30)),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=30)),
                ('identidad_genero', models.CharField(blank=True, max_length=30)),
                ('orientacion_sexual', models.CharField(blank=True, max_length=30)),
                ('tipo_documento_identidad', models.CharField(blank=True, max_length=30)),
                ('documento_identidad', models.CharField(blank=True, max_length=30)),
                ('redes_apoyo', models.TextField(blank=True)),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('comuna', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('barrio', models.CharField(blank=True, max_length=30)),
                ('ciudad_origen', models.CharField(blank=True, max_length=30, null=True)),
                ('estrato_socioeconomico', models.CharField(blank=True, max_length=30)),
                ('tipo_vbg_os', models.TextField(blank=True)),
                ('detalles_caso', models.TextField(blank=True)),
                ('ha_hecho_denuncia', models.CharField(blank=True, max_length=3)),
                ('denuncias_previas', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonaReporta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('sexo', models.CharField(blank=True, max_length=30)),
                ('edad', models.CharField(blank=True, max_length=30)),
                ('estamento', models.CharField(blank=True, max_length=30)),
                ('vicerrectoria_adscrito', models.CharField(blank=True, max_length=52)),
                ('dependencia', models.CharField(blank=True, max_length=30)),
                ('programa_academico', models.CharField(blank=True, max_length=30)),
                ('facultad', models.CharField(blank=True, max_length=30)),
                ('sede', models.CharField(blank=True, max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('condicion_etnico_racial', models.CharField(blank=True, max_length=30)),
                ('tiene_discapacidad', models.CharField(blank=True, max_length=30)),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=30)),
                ('identidad_genero', models.CharField(blank=True, max_length=30)),
                ('orientacion_sexual', models.CharField(blank=True, max_length=30)),
                ('fecha_recepcion', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cambioestado',
            name='queja_id',
        ),
        migrations.RemoveField(
            model_name='historialqueja',
            name='queja_id',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_barrio',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_celular',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_ciudad_origen',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_codigo',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_comuna',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_condicion_etnico_racial',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_correo',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_denuncias_previas',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_dependencia',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_detalles_caso',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_direccion',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_documento_identidad',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_edad',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_estamento',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_estrato_socioeconomico',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_facultad',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_ha_hecho_denuncia',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_identidad_genero',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_nombre',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_orientacion_sexual',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_programa_academico',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_redes_apoyo',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_sede',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_semestre',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_sexo',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_tiene_discapacidad',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_tipo_discapacidad',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_tipo_documento_identidad',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_tipo_vbg_os',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='afectado_vicerrectoria_adscrito',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_barrio',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_ciudad_origen',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_condicion_etnico_racial',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_dependencia',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_detalles_denuncias',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_edad',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_estamento',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_factores_riesgo',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_facultad',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_identidad_genero',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_nombre',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_orientacion_sexual',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_programa_academico',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_sede',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_semestre',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_sexo',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_tiene_denuncias',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_tiene_discapacidad',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_tipo_discapacidad',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='agresor_vicerrectoria_adscrito',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='fecha_recepcion',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='reporta_Sexo',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='reporta_celular',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='reporta_correo',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='reporta_dependencia',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='reporta_edad',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='reporta_estamento',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='reporta_facultad',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='reporta_nombre',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='reporta_programa_academico',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='reporta_sede',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='reporta_vicerrectoria_adscrito',
        ),
        migrations.AddField(
            model_name='cambioestado',
            name='queja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado', to='quejas.queja'),
        ),
        migrations.AddField(
            model_name='historialqueja',
            name='queja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_estados', to='quejas.queja'),
        ),
        migrations.AddField(
            model_name='queja',
            name='persona_acusada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quejas_como_acusado', to='quejas.personaacusada'),
        ),
        migrations.AddField(
            model_name='queja',
            name='persona_afectada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quejas_como_afectado', to='quejas.personaafectada'),
        ),
        migrations.AddField(
            model_name='queja',
            name='persona_reporta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quejas_reportadas', to='quejas.personareporta'),
        ),
    ]
