# Generated by Django 5.1.3 on 2025-10-28 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0018_personaacusada_personaafectada_personareporta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queja',
            name='persona_acusada',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='persona_afectada',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='persona_reporta',
        ),
        migrations.RemoveField(
            model_name='cambioestado',
            name='queja',
        ),
        migrations.RemoveField(
            model_name='historialqueja',
            name='queja',
        ),
        migrations.AddField(
            model_name='cambioestado',
            name='queja_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado', to='quejas.queja'),
        ),
        migrations.AddField(
            model_name='historialqueja',
            name='queja_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_estados', to='quejas.queja'),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_barrio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_celular',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_ciudad_origen',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_codigo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_comuna',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_condicion_etnico_racial',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_denuncias_previas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_dependencia',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_detalles_caso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_documento_identidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_edad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_estamento',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_estrato_socioeconomico',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_facultad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_ha_hecho_denuncia',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_identidad_genero',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_orientacion_sexual',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_programa_academico',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_redes_apoyo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_sede',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_sexo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_tiene_discapacidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_tipo_discapacidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_tipo_documento_identidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_tipo_vbg_os',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='afectado_vicerrectoria_adscrito',
            field=models.CharField(blank=True, max_length=52),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_barrio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_ciudad_origen',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_condicion_etnico_racial',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_dependencia',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_detalles_denuncias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_edad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_estamento',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_factores_riesgo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_facultad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_identidad_genero',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_orientacion_sexual',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_programa_academico',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_sede',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_sexo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_tiene_denuncias',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_tiene_discapacidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_tipo_discapacidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='agresor_vicerrectoria_adscrito',
            field=models.CharField(blank=True, max_length=52),
        ),
        migrations.AddField(
            model_name='queja',
            name='fecha_recepcion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='reporta_Sexo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='reporta_celular',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='reporta_correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='queja',
            name='reporta_dependencia',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='reporta_edad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='reporta_estamento',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='reporta_facultad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='reporta_nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='reporta_programa_academico',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='reporta_sede',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='queja',
            name='reporta_vicerrectoria_adscrito',
            field=models.CharField(blank=True, max_length=52),
        ),
        migrations.DeleteModel(
            name='PersonaAcusada',
        ),
        migrations.DeleteModel(
            name='PersonaAfectada',
        ),
        migrations.DeleteModel(
            name='PersonaReporta',
        ),
    ]
