# Generated by Django 5.1.3 on 2025-10-28 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0020_personaacusada_personaafectada_personareporta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='persona_reporta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quejas_reportadas', to='quejas.personareporta'),
        ),
    ]
