# Generated by Django 5.1.3 on 2025-10-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0021_alter_queja_persona_reporta'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='interponer_queja_a_rectoria',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='queja',
            name='interponer_queja_al_cade',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='queja',
            name='interponer_queja_oficina_control_interno',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='barrio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='ciudad_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='condicion_etnico_racial',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='dependencia',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='estamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='estrato_socioeconomico',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='facultad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='identidad_genero',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='orientacion_sexual',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='programa_academico',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='sede',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='tiene_discapacidad',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='tipo_discapacidad',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='personaafectada',
            name='vicerrectoria_adscrito',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personareporta',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
