# Generated by Django 5.1.3 on 2025-10-30 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0022_queja_interponer_queja_a_rectoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queja',
            name='interponer_queja_al_comite_asusntos_internos_disciplinarios',
        ),
    ]
