# Generated by Django 5.1.3 on 2025-02-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
