# Generated by Django 5.1.3 on 2025-03-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_workshop_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='facilitator',
        ),
        migrations.AddField(
            model_name='workshop',
            name='facilitators',
            field=models.ManyToManyField(to='talleres.facilitator'),
        ),
    ]
