# Generated by Django 5.1.3 on 2025-03-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0003_facilitator_remove_workshop_facilitator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
