# Generated by Django 5.1.3 on 2025-10-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0004_workshop_qr_code_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='qr_code_url',
        ),
        migrations.AddField(
            model_name='workshop',
            name='qr_imagen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='qr_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
