# Generated by Django 5.1.3 on 2025-10-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0004_workshop_qr_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='sede',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
