# Generated by Django 5.1.3 on 2025-10-26 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0005_remove_workshop_qr_code_url_workshop_qr_imagen_and_more'),
        ('talleres', '0005_workshop_sede'),
    ]

    operations = [
    ]
