# Generated by Django 5.1.3 on 2025-03-14 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0002_participant_gender_identity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='identity',
        ),
    ]
