# Generated by Django 5.1.3 on 2025-10-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0003_remove_participant_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='institutional_email',
        ),
    ]
