# Generated by Django 5.1.3 on 2025-10-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0004_remove_participant_institutional_email'),
        ('talleres', '0006_merge_20251025_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='document_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('workshop', 'document_number')},
        ),
    ]
