# Generated by Django 5.1.3 on 2025-10-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0005_alter_participant_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='estamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
