# Generated by Django 5.1.3 on 2025-07-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True)),
                ('status', models.CharField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('attendes', models.CharField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=8, null=True)),
                ('organizer', models.CharField(max_length=255)),
                ('startdatehour', models.DateTimeField()),
                ('enddatehour', models.DateTimeField()),
                ('timezone', models.CharField(default='America/Bogota', max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('case_id', models.CharField(max_length=100)),
                ('create_meet', models.BooleanField(blank=True, default=False, null=True)),
                ('meet_link', models.URLField(blank=True, null=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
