# Generated by Django 5.1.3 on 2025-08-12 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_event_status'),
        ('quejas', '0008_alter_queja_afectado_vicerrectoria_adscrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='case_id',
        ),
        migrations.AddField(
            model_name='event',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quejas.queja'),
        ),
    ]
