# Generated by Django 5.1.3 on 2025-08-12 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_event_case_id_event_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='case',
            new_name='case_id',
        ),
    ]
