# Generated by Django 5.1.3 on 2025-10-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
