# Generated by Django 5.1.3 on 2025-10-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_event_google_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
