# Generated by Django 5.1.3 on 2025-10-30 19:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_alter_event_attendes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, null=True, size=None),
        ),
    ]
