# Generated by Django 5.1.3 on 2024-12-05 02:24

import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_usuarios_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restore_Password_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=login.models.generar_codigo, max_length=6, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
