# Generated by Django 5.1.3 on 2025-01-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_restore_password_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quejas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.CharField(max_length=30)),
                ('reporta_nombre', models.CharField(max_length=30)),
                ('reporta_Sexo', models.CharField(max_length=30)),
                ('reporta_edad', models.CharField(max_length=30)),
                ('reporta_estamento', models.CharField(max_length=30)),
                ('reporta_vicerrectoria_adscrito', models.CharField(max_length=30)),
                ('reporta_dependencia', models.CharField(max_length=30)),
                ('reporta_programa_academico', models.CharField(max_length=30)),
                ('reporta_facultad', models.CharField(max_length=30)),
                ('reporta_sede', models.CharField(max_length=30)),
                ('reporta_celular', models.CharField(max_length=30)),
                ('reporta_correo', models.CharField(max_length=30)),
                ('afectado_nombre', models.CharField(max_length=30)),
                ('afectado_sexo', models.CharField(max_length=30)),
                ('afectado_edad', models.CharField(max_length=30)),
                ('afectado_comuna', models.CharField(max_length=30)),
                ('afectado_estrato_socioeconomico', models.CharField(max_length=30)),
                ('afectado_condicion_etnico_racial', models.CharField(max_length=30)),
                ('afectado_tiene_discapacidad', models.CharField(max_length=30)),
                ('afectado_tipo_discapacidad', models.CharField(max_length=30)),
                ('afectado_identidad_genero', models.CharField(max_length=30)),
                ('afectado_orientacion_sexual', models.CharField(max_length=30)),
                ('afectado_estamento', models.CharField(max_length=30)),
                ('afectado_vicerrectoria_adscrito', models.CharField(max_length=30)),
                ('afectado_dependencia', models.CharField(max_length=30)),
                ('afectado_programa_academico', models.CharField(max_length=30)),
                ('afectado_facultad', models.CharField(max_length=30)),
                ('afectado_sede', models.CharField(max_length=30)),
                ('afectado_celular', models.CharField(max_length=30)),
                ('afectado_correo', models.CharField(max_length=30)),
                ('afectado_tipo_vbg_os', models.CharField(max_length=30)),
                ('afectado_detalles_caso', models.CharField(max_length=30)),
                ('agresor_nombre', models.CharField(max_length=30)),
                ('agresor_sexo', models.CharField(max_length=30)),
                ('agresor_edad', models.CharField(max_length=30)),
                ('agresor_condicion_etnico_racial', models.CharField(max_length=30)),
                ('agresor_tiene_discapacidad', models.CharField(max_length=30)),
                ('agresor_tipo_discapacidad', models.CharField(max_length=30)),
                ('agresor_identidad_genero', models.CharField(max_length=30)),
                ('agresor_orientacion_sexual', models.CharField(max_length=30)),
                ('agresor_estamento', models.CharField(max_length=30)),
                ('agresor_vicerrectoria_adscrito', models.CharField(max_length=30)),
                ('agresor_dependencia', models.CharField(max_length=30)),
                ('agresor_programa_academico', models.CharField(max_length=30)),
                ('agresor_facultad', models.CharField(max_length=30)),
                ('agresor_sede', models.CharField(max_length=30)),
                ('desea_activar_ruta_atencion_integral', models.CharField(max_length=30)),
                ('requiere_recibir_asesoria_orientacion_sociopedagogica', models.CharField(max_length=30)),
                ('requiere_orientacion_psicologica', models.CharField(max_length=30)),
                ('requiere_asistencia_juridica', models.CharField(max_length=30)),
                ('requiere_acompañamiento_solicitud_medidas_proteccion_inicial', models.CharField(max_length=30)),
                ('requiere_acompañamiento_ante_instancias_gubernamentales', models.CharField(max_length=30)),
                ('requiere_interponer_queja_al_comite_asusntos_internos_disciplinarios', models.CharField(max_length=30)),
                ('observaciones', models.CharField(max_length=500)),
            ],
        ),
    ]
