# Generated by Django 5.1.3 on 2025-01-31 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_quejas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quejas',
            old_name='requiere_acompañamiento_ante_instancias_gubernamentales',
            new_name='acompañamiento_ante_instancias_gubernamentales',
        ),
        migrations.RenameField(
            model_name='quejas',
            old_name='requiere_acompañamiento_solicitud_medidas_proteccion_inicial',
            new_name='acompañamiento_solicitud_medidas_proteccion_inicial',
        ),
        migrations.RenameField(
            model_name='quejas',
            old_name='requiere_asistencia_juridica',
            new_name='asistencia_juridica',
        ),
        migrations.RenameField(
            model_name='quejas',
            old_name='requiere_interponer_queja_al_comite_asusntos_internos_disciplinarios',
            new_name='interponer_queja_al_comite_asusntos_internos_disciplinarios',
        ),
        migrations.RenameField(
            model_name='quejas',
            old_name='requiere_orientacion_psicologica',
            new_name='orientacion_psicologica',
        ),
        migrations.RenameField(
            model_name='quejas',
            old_name='requiere_recibir_asesoria_orientacion_sociopedagogica',
            new_name='recibir_asesoria_orientacion_sociopedagogica',
        ),
    ]
