# Generated by Django 5.1.3 on 2025-01-31 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_rename_requiere_acompañamiento_ante_instancias_gubernamentales_quejas_acompañamiento_ante_instancias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quejas',
        ),
    ]
