# Generated by Django 5.1.3 on 2025-08-26 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_usuarios_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_type', models.CharField(default='Bearer', max_length=20)),
                ('scope', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_oauth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
