"""
Django settings for appvbgbackend project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Cargar las variables de entorno
load_dotenv()

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = "postmessage"


##Manejo de Cookies
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True  # Cambia a True en producción con HTTPS
#SESSION_COOKIE_NAME = "sessionid"

CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = True  # Cambia a True en producción con HTTPS
SESSION_SAVE_EVERY_REQUEST = False


SESSION_ENGINE = "django.contrib.sessions.backends.db"

##CORS

CORS_ALLOW_CREDENTIALS = True  # Permite el envío de cookies o tokens de autenticación
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://localhost:3000", 
    "https://127.0.0.1:3000",
    "https://dtweetsjnyccweomsrvf.supabase.co",
    "https://app-gestion-casos-vbg-frontend.vercel.app",
    "https://app-gestion-casos-vbg-frontend-alejandros-projects-0a22a2ff.vercel.app",
    "https://app-gestion-casos-vbg-f-git-bca302-alejandros-projects-0a22a2ff.vercel.app",
    "https://app-gestion-casos-vbg-frontend-id41xzawc.vercel.app",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://localhost:3000", 
    "https://127.0.0.1:3000",
    "https://dtweetsjnyccweomsrvf.supabase.co",
    "https://app-gestion-casos-vbg-frontend.vercel.app",
    "https://app-gestion-casos-vbg-frontend-alejandros-projects-0a22a2ff.vercel.app",
    "https://app-gestion-casos-vbg-f-git-bca302-alejandros-projects-0a22a2ff.vercel.app",
    "https://app-gestion-casos-vbg-frontend-id41xzawc.vercel.app",
]




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_+k%u()ao&t4_b#5rre#_igz_ozt$)s7k_k#skfdj#limw%77_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # Cambia a False en producción

ALLOWED_HOSTS = [
    'appgestioncasosvbg-backend.onrender.com',
    'localhost',
    '127.0.0.1',
    '.onrender.com'
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'login',
    'corsheaders',
    ##'quejas', usar esta si la de abajo se rompe
    'quejas.apps.QuejasConfig',
    'talleres',
    'participantes',
    'agenda',
    'django_extensions',
]

'''AUTHENTICATION_BACKENDS = [
    'login.authentication.EmailAuthBackend',  # Ruta al backend personalizado  # Backend de Django
]'''

AUTH_USER_MODEL = 'login.Usuarios'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'appvbgbackend.urls'




TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'appvbgbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#       'NAME': 'vbgdb',  # Nombre de tu base de datos
#       'USER': 'postgres',                  # Usuario de PostgreSQL
#       'PASSWORD': 'invitado',           # Contraseña del usuario
#       'HOST': 'localhost',                  # Si está en el mismo equipo
#      'PORT': '5432',                        # Puerto por defecto de PostgreSQL
#    }   
#}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', 'postgres.dtweetsjnyccweomsrvf'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'aws-1-us-east-1.pooler.supabase.com'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'sslmode': 'require',
            'connect_timeout': 5,
        },
        'CONN_MAX_AGE': 180,
        'DISABLE_SERVER_SIDE_CURSORS': True,
    }
}


#Email Data
###Ingresar los datos del correo
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Proveedor SMTP, como Gmail (smtp.gmail.com)
EMAIL_PORT = 587  # Generalmente es 587 para conexiones seguras
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'dawntest90@gmail.com'  # Tu correo electrónico
EMAIL_HOST_PASSWORD = 'brxz cals xvjk zhvh'  # Tu contrasena
DEFAULT_FROM_EMAIL = 'dawntest90@gmail.com'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'